apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: sandbox
  labels:
    name:  zookeeper-service
    environment: Development
spec:
  type: NodePort
  selector:
    name: zookeeper-pod
    environment: Development
  ports:
  - name:  zookeeper-port
    port:  2181
    protocol: TCP