apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
  namespace: sandbox
  labels:
    name: kafka-configmap
    environment: Development
data:
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service.sandbox:2181"
  KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-service.sandbox:9092,EXTERNAL://192.168.58.2:32554
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  DYNAMIC_CONFIG_ENABLED: "true"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "http://192.168.58.2:32554"