apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: sandbox
  labels:
    name:  kafka-service
    environment: Development
spec:
  type: NodePort
  selector:
    name: kafka-pod
    environment: Development
  ports:
  - name:  kafka-port
    port:  9092
    protocol: TCP