apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: sandbox
  labels:
    name:  postgres-pv
    environment: Development
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: standard
  capacity:
    storage: 10Gi
  hostPath:
    path:  /home/mrrobot/Volumes/Postgresql
