kind: Service
apiVersion: v1
metadata:
  name:  postgres-service
  namespace: sandbox
spec:
  type: NodePort
  selector:
    name: PostgresPOD
    environment: Development
  ports:
  - name:  postgres-port
    port:  5432
    targetPort:  5432