apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sandbox
  labels:
    environment: Development
    name: PostgresDeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: PostgresPOD
  template:
    metadata:
      name: postgres-pod
      labels:
        name: PostgresPOD
        environment: Development
    spec:
      containers:
      - name: postgres-db
        image: postgres
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-db-configmap
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "1024Mi"
      volumes:
      - name:  postgres-volume
        persistentVolumeClaim:
          claimName: postgres-pvc